### PR TITLE
config: stop using tikv's config struct; error on unrecognized fields

### PR DESCRIPTION
**Pull request by kennytm**
## What have you changed? (mandatory)

Emit an error and quit if tikv-importer's config file contains any unrecognized fields.

The error is natively supported by serde via the `#[serde(deny_unknown_fields)]` container attribute. However, since TiKV's config structs don't have this attribute yet, we replicate that structure into this project (which is a TODO for us anyway).

Also, upgraded the Importer version to 3.0.2.

## What are the type of the changes? (mandatory)

- New feature (change which adds functionality)

## How has this PR been tested? (mandatory)

Unit test.

## Does this PR affect TiDB Lightning? (mandatory)

No.

### CODE REVIEW

**Comment by kennytm** [comment]
PTAL @lance6716 @WangXiangUSTC

**Comment by lance6716** [comment]
LGTM

**Comment by WangXiangUSTC** [comment]
LGTM

**Review by WangXiangUSTC — APPROVED** [review]

**Pull request merged**
