### PR TITLE
*: Strip the first 11 bytes from key in WriteEngine, specify it in OpenEngine

### PR DESCRIPTION
**Pull request by lance6716**
## What have you changed? (mandatory)

Please explain **IN DETAIL** what the changes are in this PR and why they are needed:
- Summarize your change (mandatory)
  - specify prefix for same table to reduce transport data, as in [kvproto#451](https://github.com/pingcap/kvproto/pull/451)
- How does this PR work? Need a brief introduction for the changed logic (optional)
  - When write to `RawBatch`, concatenate prefix to recover full key
- Separately describe each logical change and avoid lazy messages (optional)
- Describe any limitations of the current code (optional)

Please **NOTE** that:
- Do not assume reviewers understand the original issue

## What are the type of the changes? (mandatory)

The currently defined types are listed below, please pick one of the types for this PR by removing the others:
- Improvement (change which is an improvement to an existing feature)

## How has this PR been tested? (mandatory)

Unit test, integration test with [lightning#236](https://github.com/pingcap/tidb-lightning/pull/236)

## Does this PR affect TiDB Lightning? (mandatory)

[lightning#236](https://github.com/pingcap/tidb-lightning/pull/236)

## Refer to a related PR or issue link (optional)

#5 , [kvproto#451](https://github.com/pingcap/kvproto/pull/451)

### CODE REVIEW

**Comment by lance6716** [comment]
currently block by 

~1. Not rebase~
~2. Lightning RPC broken~

**Comment by kennytm** [comment]
I don't think this will break Lightning. Given how gRPC works, the extra field of the OpenRequest will just be set to NULL when missing.

**Comment by lance6716** [comment]
PTAL @kennytm @overvenus

**Comment by lance6716** [comment]
PTAL @breeswish

**Comment by kennytm** [comment]
Unfortunately we need to put this PR on hold because BR may have a different strategy about where to add the prefixes.

**Comment by lance6716** [comment]
Stages later than `OpenEngine` need key converting between raw and encoded, I haven't attempted if conversion has other problems

**Comment by kennytm** [comment]
Well that's the point 😅.

We'll report back next week.

**Comment by kennytm** [comment]
We've discussed that this feature will be implemented directly inside TiKV. Thus this PR is no longer the correct approach and I'm closing it. Thanks for the work :).

**Pull request closed without merging**
