### PR TITLE
Cargo.toml: set version to 3.0.4

### PR DESCRIPTION
**Pull request by kennytm**
## What have you changed? (mandatory)

Set version to v3.0.4.

## What are the type of the changes? (mandatory)

- Engineering (engineering change which doesn't change any feature or fix any issue)

## How has this PR been tested? (mandatory)

N/A

## Does this PR affect TiDB Lightning? (mandatory)

No

### CODE REVIEW

**Comment by kennytm** [comment]
PTAL @ericsyh @lance6716

**Comment by lance6716** [comment]
LGTM

**Comment by ericsyh** [comment]
LGTM

**Pull request merged**
