### PR TITLE
*: Use lower version of openssl and make more functions async

### PR DESCRIPTION
**Pull request by kennytm**
## What have you changed? (mandatory)

**1.** Use the same locked OpenSSL version as TiKV (1.1.1g) instead of the latest one (1.1.1i)

Fix this error when connecting to importer:

```
[2020-12-28T03:23:43.689Z] [2020/12/28 11:23:39.020 +08:00] [ERROR] [<unknown>] ["Handshake failed with fatal error SSL_ERROR_SSL: error:1417C086:SSL routines:tls_process_client_certificate:certificate verify failed."]
```

We may need to check the cert generation algorithm in Lightning to ensure nothing goes wrong when we actually upgrade OpenSSL to 1.1.1i.

**2.** Make more functions relying on `block_on` as async, to avoid the `EnterError` when using `block_on` inside an async context.

## What are the type of the changes? (mandatory)

- Bug fix (change which fixes an issue)

## How has this PR been tested? (mandatory)

run the Lightning integration test `various_types`.

## Does this PR affect TiDB Lightning? (mandatory)

No

### CODE REVIEW

**Comment by overvenus** [comment]
LGTM

**Comment by kennytm** [comment]
Blocked by cherry-pick of tikv/tikv#9390 to release-5.0-rc.

**Review by Little-Wallace — APPROVED** [review]
LGTM

**Review by glorv — APPROVED** [review]
LGTM

**Review by zhangjinpeng87 — APPROVED** [review]

**Review by jebter — APPROVED** [review]

**Pull request merged**
