### PR TITLE
Cargo.toml: update dependencies and set version to 3.0.5

### PR DESCRIPTION
**Pull request by kennytm**
## What have you changed? (mandatory)

Update TiKV dependency to v3.0.4.

## What are the type of the changes? (mandatory)

- Engineering (engineering change which doesn't change any feature or fix any issue)

## How has this PR been tested? (mandatory)

`cargo test`

## Does this PR affect TiDB Lightning? (mandatory)

No

### CODE REVIEW

**Comment by kennytm** [comment]
PTAL @3pointer @WangXiangUSTC cc @ericsyh

**Comment by WangXiangUSTC** [comment]
LGTM

**Comment by kennytm** [comment]
Ping @3pointer / PTAL @GregoryIan

**Comment by 3pointer** [comment]
LGTM

**Pull request merged**
