### PR TITLE
kv_server: make the receive message size unlimited (#26)

### PR DESCRIPTION
**Pull request by kennytm**
## What have you changed? (mandatory)

Cherry-picks #26 to release-3.0.

## What are the type of the changes? (mandatory)

- Bug fix (change which fixes an issue)

## How has this PR been tested? (mandatory)

-

## Does this PR affect TiDB Lightning? (mandatory)

No

### CODE REVIEW

**Comment by kennytm** [comment]
/run-all-tests tikv=release-3.0 tidb=release-3.0 pd=release-3.0

**Comment by ericsyh** [comment]
@kennytm pls fix the ci.

**Comment by kennytm** [comment]
@ericsyh it is caused by lack of memory in the container. Currently being fixed by SRE team.

**Comment by ericsyh** [comment]
/run-all-tests tikv=release-3.0 tidb=release-3.0 pd=release-3.0

**Comment by ericsyh** [comment]
/run-all-tests tikv=release-3.0 tidb=release-3.0 pd=release-3.0

**Comment by kennytm** [comment]
PTAL  @overvenus  @5kbpers

**Review by 5kbpers — APPROVED** [review]
LGTM

**Review by overvenus — APPROVED** [review]

**Pull request merged**
