### PR TITLE
*: quick-error -> thiserror, fmt

### PR DESCRIPTION
**Pull request by PsiACE**
Signed-off-by: Chojan Shang <psiace@outlook.com>

## What have you changed? (mandatory)

- quick-error -> thiserror
- cargo fmt
- update travis ci config

## What are the type of the changes? (mandatory)

- Engineering (engineering change which doesn't change any feature or fix any issue)

## How has this PR been tested? (mandatory)

Test with travis ci , `make build` & `make test`.

## Does this PR affect TiDB Lightning? (mandatory)

I don't think so.

### CODE REVIEW

**Comment by PsiACE** [comment]
so, what happened? this doesn't seem to be my problem.

**Comment by purelind** [comment]
> so, what happened? this doesn't seem to be my problem.

It seems that build meet some error on new ci. I will try it later

**Comment by PsiACE** [comment]
Sorry, too many errors, I will fix these in the next commit

**Comment by PsiACE** [comment]
Welcome to thiserror

Sorry, there are too many commits, please squash before merging.

**Comment by PsiACE** [comment]
ping @purelind cc @kennytm

**Review by kennytm — APPROVED** [review]

**Pull request merged**
